[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$cO69t3auFULIGcMY4xxjTA$4w6HkNE0ZqW9QZmhRuh05p2STmszOojsYWdZFQ.R/8Q4BshdxSdW1cVVpf2n1Pr14t8FaIxxu.JNErmWt1yv2w
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

